apiVersion: v1
kind: Secret
metadata:
  name: social-secrets
  namespace: socialmedia
type: Opaque
stringData:
  secret-key: cveDeg-xyE35PWjLc2RtBtQb7q3ooK5tES1UDh1U29jTWtOditjeC83qfoBYj9O0bMc
  db-password: SocialP@5432
  email-password: SocialP@5432
