apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    type: local
    app: social-media
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /data/SocialMedia/media
    tpe: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: socialmedia
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      app: social-media

