apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  labels:
    type: local
    app: social-media
spec:
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/SocialMedia/static
    type: DirecttoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: socialmedia
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 9Gi
  selector:
    matchLebels:
      type: local
      app: social-media
