apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: socialmedia
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu:  "500m"
        env:
        - name: POSTGRES_DB
          value: "socialmedia"
        - name: POSTGRES_USER
          value: "django"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
